### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by rodrigograca31** [achtan/infinite-todo#1]
Hi!

I was looking for something like this, an infinite checklist that I cant "re-check" for ever.....
The README.md file doesn't contain any information on how I can make the project work....

(BTW, I'm not familiar with meteor....)

Thanks.

**Comment by achtan** [comment]
hi, I updated readme.

i'm glad that you're interested in my project. May I ask what is your use case?

**Comment by rodrigograca31** [comment]
Sometimes I make checklist for some processes and then later I check the list and uncheck it to check again in the future....
